# Generated by Django 5.1.4 on 2025-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gmail', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('insta_link', models.CharField(max_length=255)),
                ('telegram_link', models.CharField(max_length=255)),
            ],
        ),
    ]
