# Generated by Django 5.1.4 on 2025-08-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('darajangiz', models.CharField(max_length=255)),
                ('information_about_yourself', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gmail', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('insta_link', models.URLField()),
                ('telegram_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='project_image')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.CharField(max_length=1000)),
                ('project_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('files', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skils_name', models.CharField(max_length=255)),
                ('skils_logo', models.ImageField(upload_to='skils_logo')),
            ],
        ),
    ]
