# Generated by Django 5.1.4 on 2025-08-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('darajangiz', models.CharField(max_length=255)),
                ('information_about_yourself', models.CharField(max_length=255)),
                ('skils', models.CharField(max_length=255)),
                ('skils_logo', models.ImageField(upload_to='skils_logo')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='insta_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='telegram_link',
            field=models.URLField(),
        ),
    ]
