# Generated by Django 5.1.4 on 2025-08-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='files',
            new_name='file',
        ),
    ]
