# Generated by Django 5.1.4 on 2025-08-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_home_alter_menu_insta_link_alter_menu_telegram_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='skils',
        ),
        migrations.RemoveField(
            model_name='home',
            name='skils_logo',
        ),
    ]
