# Generated by Django 5.1.4 on 2025-08-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_home_skils_remove_home_skils_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skils', models.CharField(max_length=255)),
                ('skils_logo', models.ImageField(upload_to='skils_logo')),
            ],
        ),
    ]
