# Generated by Django 5.1.4 on 2025-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='information_about_yourself',
            field=models.CharField(max_length=1000),
        ),
    ]
