# Generated by Django 5.1.4 on 2025-08-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_home_information_about_yourself'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skils',
            old_name='skils',
            new_name='skils_name',
        ),
    ]
