# Generated by Django 5.1.4 on 2025-08-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_skils_skils_skils_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skils',
            name='skils_logo',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
