# Generated by Django 5.1.4 on 2025-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_skils_skils_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skils',
            name='skils_logo',
            field=models.ImageField(upload_to='skils_logo'),
        ),
    ]
