# Generated by Django 5.1.4 on 2025-08-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_skils_skils_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='project_image')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.CharField(max_length=1000)),
                ('project_link', models.URLField()),
            ],
        ),
    ]
